---
title: "Writing Functions"
author: "Rachel Lee"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data}

library(tidyverse)
library(rvest)

set.seed(1)

```

Section: My First Function 

```{r firstfunction}

x_vec = rnorm(25, mean = 5, sd = 3)

#computing z score w/o writing a function
(x_vec - mean(x_vec)) / sd(x_vec) 

#computing z score w/ a function
z_scores = function(x) {
  z = (x - mean(x)) / sd(x) 
  z #return z
}

z_scores(x_vec)


#adding conditional statements 

z_scores = function(x) {
  if(!is.numeric(x)){
    stop("Argument x should be numeric")
  } else if (length(x) == 1){
    stop("Z scores cannot be computed for length 1 vectors")
  }

  z = mean(x) / sd(x)
  z
}


```



```{r MultipleOutputs}

mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  #store values in a list and return
  list(mean = mean_x,
       sd = sd_x)
}




mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  #store values in a table and return
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}

```



```{r MultipleInputs}

sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

#plotting sim_data
sim_data %>%
  ggplot(aes(x = x, y = y)) + 
  geom_point()

# linear regression line
ls_fit = lm(y ~ x, data = sim_data)

#returns the estimated intercept and slope
beta0_hat = coef(ls_fit)[1] #intercept
beta1_hat = coef(ls_fit)[2] #slope

#rnorm generates a vector of normally distributed random numbers 

sim_regression = function(n, beta0 = 2, beta1 = 3) {
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y~x, data = sim_data)
  
  tibble(
     beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}

sim_regression(300)

```




